version: '3'
services:
  portall:
    build: .
    container_name: portal
    ports:
      - "8982:8080"
    environment:
      - SECRET_KEY=erhrehrfrdt
      - DOCKER_HOST=unix://var/run/docker.sock
    volumes:
      - ./instance:/app/instance
      - /var/run/docker.sock:/var/run/docker.sock